### ISSUE TITLE
TA Comment - 需求構想書

### ISSUE THREAD

**Issue by jo-ym** [joonkui95/ShenLaiYe#1]
檔名格式應該是<組名>\_需求構想書\_.doc or .docx

**Comment by ahkui** [comment]
@TDyu 所以是這樣【神來也需求構想書.docx】？

**Comment by jo-ym** [comment]
是這樣才對 : 神來也\_需求構想書\_.doc or .docx
(我一開始留comment時忘了Markdown的語法...所以沒有讓底線顯示出來...抱歉)
你們一開始少了個\_

**Comment by ahkui** [comment]
哦好明白
